// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO8TDQaOhy_ktO3SBZbmYQ3kNNOg__ht8',
    appId: '1:426361685214:web:e6c77272727a936449ae4f',
    messagingSenderId: '426361685214',
    projectId: 'notes-cb2d2',
    authDomain: 'notes-cb2d2.firebaseapp.com',
    databaseURL: 'https://notes-cb2d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-cb2d2.appspot.com',
    measurementId: 'G-CSDN47X4R9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zDJF60xuHmy9Ro33NAlpX9_bjgaPsaE',
    appId: '1:426361685214:android:b4be300eddc99b0d49ae4f',
    messagingSenderId: '426361685214',
    projectId: 'notes-cb2d2',
    databaseURL: 'https://notes-cb2d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-cb2d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16SZV5Bh0e_C-2nLZktw240l-nBDMx28',
    appId: '1:426361685214:ios:1bdb0b8457e1fa5849ae4f',
    messagingSenderId: '426361685214',
    projectId: 'notes-cb2d2',
    databaseURL: 'https://notes-cb2d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-cb2d2.appspot.com',
    iosBundleId: 'io.gobpo2002.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16SZV5Bh0e_C-2nLZktw240l-nBDMx28',
    appId: '1:426361685214:ios:1bdb0b8457e1fa5849ae4f',
    messagingSenderId: '426361685214',
    projectId: 'notes-cb2d2',
    databaseURL: 'https://notes-cb2d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-cb2d2.appspot.com',
    iosBundleId: 'io.gobpo2002.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAO8TDQaOhy_ktO3SBZbmYQ3kNNOg__ht8',
    appId: '1:426361685214:web:c2dc15a437f6cc3c49ae4f',
    messagingSenderId: '426361685214',
    projectId: 'notes-cb2d2',
    authDomain: 'notes-cb2d2.firebaseapp.com',
    databaseURL: 'https://notes-cb2d2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-cb2d2.appspot.com',
    measurementId: 'G-BFRR89TVHT',
  );
}
